package formulario;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Jose Felix
 */
public class JFAaltas extends javax.swing.JFrame {
    private Connection conexion;
    private Statement st;
    private ResultSet rs;
    public void Conectar(){
        try{
        conexion=DriverManager.getConnection("jdbc:mysql://localhost:3307/proyecto","root","");
            st=conexion.createStatement();
            rs=st.executeQuery("Select * from prod_existencia");
        
            rs.next();
        
        this.jtf_codigo.setText(rs.getString("codigo"));
        this.jtf_marca.setText(rs.getString("marca"));
        this.jtf_modelo.setText(rs.getString("modelo"));
        this.jtf_precio_compra.setText(rs.getString("precio_de_compra"));
        this.jtf_precio_venta.setText(rs.getString("precio_de_venta"));
        this.jtf_cantidad_productos.setText(rs.getString("cantidad_prod"));
        this.jtf_talla.setText(rs.getString("talla"));
        this.jtf_color.setText(rs.getString("color"));
        this.jtf_fecha.setText(rs.getString("fecha_ingreso"));
        jb_guardar.setVisible(false);
        jb_actualizar.setVisible(false);
        jb_cancelar.setVisible(false);
        }catch(SQLException err){
            JOptionPane.showMessageDialog(null,"Error"+err.getMessage());
        }
    }

    /**
     * Creates new form altas
     */
    public JFAaltas() {
        initComponents();
        this.Conectar();
    }
    public void moverPrimerRegistro() {
        try {
            rs.first();
            llenarDatos();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error 001" + ex.getMessage());
        }
    }

    public void moverRegistroSiguiente() {
        try {
            if (!rs.isLast()) {
                rs.next();
                llenarDatos();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error 001" + ex.getMessage());
        }
    }
    
    public void moverRegistroAnterior() {
        try {
            if (!rs.isFirst()) {
                rs.previous();
                llenarDatos();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error 001" + ex.getMessage());
        }
    }
    
    public void moverUltimoRegistro() {
        try {
            rs.last();
            llenarDatos();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error 001" + ex.getMessage());
        }
    }

    public void llenarDatos() {
        try {
            this.jtf_codigo.setText(rs.getString("codigo"));
            this.jtf_marca.setText(rs.getString("marca"));
            this.jtf_modelo.setText(rs.getString("modelo"));
            this.jtf_precio_compra.setText(rs.getString("precio_de_compra"));
            this.jtf_precio_venta.setText(rs.getString("precio_de_venta"));
            this.jtf_cantidad_productos.setText(rs.getString("cantidad_prod"));
            this.jtf_talla.setText(rs.getString("talla"));
            this.jtf_color.setText(rs.getString("color"));
            this.jtf_fecha.setText(rs.getString("fecha_ingreso"));
            jb_guardar.setVisible(false);
            jb_actualizar.setVisible(false);
            jb_cancelar.setVisible(false);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error 002" + ex.getMessage());
        }
    }
    public void deshabilitarEdicion(){
        jtf_codigo.setEditable(false);
        jtf_modelo.setEditable(false);
        jtf_marca.setEditable(false);
        jtf_precio_compra.setEditable(false);
        jtf_precio_venta.setEditable(false);
        jtf_cantidad_productos.setEditable(false);
        jtf_talla.setEditable(false);
        jtf_color.setEditable(false);
        jtf_fecha.setVisible(true);
        jl_fecha.setVisible(true);
}
     public void habilitarEdicion(){
        jtf_codigo.setEditable(false);
        jtf_modelo.setEditable(true);
        jtf_marca.setEditable(true);
        jtf_precio_compra.setEditable(true);
        jtf_precio_venta.setEditable(true);
        jtf_cantidad_productos.setEditable(true);
        jtf_talla.setEditable(true);
        jtf_color.setEditable(true);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jl_codigo = new javax.swing.JLabel();
        jl_modelo = new javax.swing.JLabel();
        jl_marca = new javax.swing.JLabel();
        jl_precio_compra = new javax.swing.JLabel();
        jl_precio_venta = new javax.swing.JLabel();
        jl_cantidad_productos = new javax.swing.JLabel();
        jl_talla = new javax.swing.JLabel();
        jl_color = new javax.swing.JLabel();
        jtf_codigo = new javax.swing.JTextField();
        jtf_modelo = new javax.swing.JTextField();
        jtf_marca = new javax.swing.JTextField();
        jtf_precio_compra = new javax.swing.JTextField();
        jtf_precio_venta = new javax.swing.JTextField();
        jtf_cantidad_productos = new javax.swing.JTextField();
        jtf_talla = new javax.swing.JTextField();
        jtf_color = new javax.swing.JTextField();
        jtf_fecha = new javax.swing.JTextField();
        jl_fecha = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jb_nuevo = new javax.swing.JButton();
        jb_borrar = new javax.swing.JButton();
        jb_modificar = new javax.swing.JButton();
        jb_guardar = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();
        jb_salir = new javax.swing.JButton();
        jb_actualizar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jb_primer_registro = new javax.swing.JButton();
        jb_registro_anterior = new javax.swing.JButton();
        jb_siguiente_registro = new javax.swing.JButton();
        jb_ultimo_registro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(255, 204, 204));

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/Resize Image_1533787075919.jpg"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(0, 0, 153));
        jLabel1.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRODUCTOS");
        jLabel1.setFocusTraversalPolicyProvider(true);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jl_codigo.setBackground(new java.awt.Color(153, 204, 255));
        jl_codigo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_codigo.setText("Codigo");
        jl_codigo.setOpaque(true);

        jl_modelo.setBackground(new java.awt.Color(153, 204, 255));
        jl_modelo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_modelo.setText("Modelo");
        jl_modelo.setOpaque(true);

        jl_marca.setBackground(new java.awt.Color(153, 204, 255));
        jl_marca.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_marca.setText("Marca");
        jl_marca.setOpaque(true);

        jl_precio_compra.setBackground(new java.awt.Color(153, 204, 255));
        jl_precio_compra.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_precio_compra.setText("Precio de compra");
        jl_precio_compra.setOpaque(true);

        jl_precio_venta.setBackground(new java.awt.Color(153, 204, 255));
        jl_precio_venta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_precio_venta.setText("Precio de venta");
        jl_precio_venta.setOpaque(true);

        jl_cantidad_productos.setBackground(new java.awt.Color(153, 204, 255));
        jl_cantidad_productos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_cantidad_productos.setText("Cantidad de productos ");
        jl_cantidad_productos.setOpaque(true);

        jl_talla.setBackground(new java.awt.Color(153, 204, 255));
        jl_talla.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_talla.setText("Talla");
        jl_talla.setOpaque(true);

        jl_color.setBackground(new java.awt.Color(153, 204, 255));
        jl_color.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_color.setText("Color");
        jl_color.setOpaque(true);

        jtf_codigo.setEditable(false);
        jtf_codigo.setBackground(new java.awt.Color(153, 255, 255));
        jtf_codigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_modelo.setEditable(false);
        jtf_modelo.setBackground(new java.awt.Color(153, 255, 255));
        jtf_modelo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_marca.setEditable(false);
        jtf_marca.setBackground(new java.awt.Color(153, 255, 255));
        jtf_marca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtf_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_marcaActionPerformed(evt);
            }
        });

        jtf_precio_compra.setEditable(false);
        jtf_precio_compra.setBackground(new java.awt.Color(153, 255, 255));
        jtf_precio_compra.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_precio_venta.setEditable(false);
        jtf_precio_venta.setBackground(new java.awt.Color(153, 255, 255));
        jtf_precio_venta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_cantidad_productos.setEditable(false);
        jtf_cantidad_productos.setBackground(new java.awt.Color(153, 255, 255));
        jtf_cantidad_productos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_talla.setEditable(false);
        jtf_talla.setBackground(new java.awt.Color(153, 255, 255));
        jtf_talla.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_color.setEditable(false);
        jtf_color.setBackground(new java.awt.Color(153, 255, 255));
        jtf_color.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_fecha.setEditable(false);
        jtf_fecha.setBackground(new java.awt.Color(153, 255, 255));
        jtf_fecha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jl_fecha.setBackground(new java.awt.Color(153, 204, 255));
        jl_fecha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_fecha.setText("Fecha");
        jl_fecha.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jl_codigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addComponent(jtf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_modelo)
                            .addComponent(jl_marca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtf_marca, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                            .addComponent(jtf_modelo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_precio_compra)
                            .addComponent(jl_precio_venta)
                            .addComponent(jl_cantidad_productos)
                            .addComponent(jl_talla)
                            .addComponent(jl_color)
                            .addComponent(jl_fecha))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_fecha, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtf_talla, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtf_cantidad_productos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtf_precio_venta)
                            .addComponent(jtf_precio_compra)
                            .addComponent(jtf_color))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_codigo)
                    .addComponent(jtf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jl_modelo)
                    .addComponent(jtf_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_marca)
                    .addComponent(jtf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_precio_compra)
                    .addComponent(jtf_precio_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_precio_venta)
                    .addComponent(jtf_precio_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_cantidad_productos)
                    .addComponent(jtf_cantidad_productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_talla)
                    .addComponent(jtf_talla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_color)
                    .addComponent(jtf_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_fecha))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jb_nuevo.setBackground(new java.awt.Color(51, 0, 255));
        jb_nuevo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        jb_nuevo.setText("Nuevo");
        jb_nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_nuevoMouseClicked(evt);
            }
        });

        jb_borrar.setBackground(new java.awt.Color(51, 51, 255));
        jb_borrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_borrar.setForeground(new java.awt.Color(255, 255, 255));
        jb_borrar.setText("Borrar");
        jb_borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_borrarMouseClicked(evt);
            }
        });

        jb_modificar.setBackground(new java.awt.Color(51, 0, 255));
        jb_modificar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_modificar.setForeground(new java.awt.Color(255, 255, 255));
        jb_modificar.setText("Modificar");
        jb_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modificarMouseClicked(evt);
            }
        });

        jb_guardar.setBackground(new java.awt.Color(51, 0, 255));
        jb_guardar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_guardar.setForeground(new java.awt.Color(255, 255, 255));
        jb_guardar.setText("Guardar");
        jb_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarMouseClicked(evt);
            }
        });
        jb_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_guardarActionPerformed(evt);
            }
        });

        jb_cancelar.setBackground(new java.awt.Color(51, 0, 204));
        jb_cancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        jb_cancelar.setText("Cancelar");
        jb_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_cancelarMouseClicked(evt);
            }
        });

        jb_salir.setBackground(new java.awt.Color(51, 0, 255));
        jb_salir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_salir.setForeground(new java.awt.Color(255, 255, 255));
        jb_salir.setText("Salir");
        jb_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_salirMouseClicked(evt);
            }
        });

        jb_actualizar.setBackground(new java.awt.Color(51, 0, 255));
        jb_actualizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_actualizar.setForeground(new java.awt.Color(255, 255, 255));
        jb_actualizar.setText("Actualizar");
        jb_actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_actualizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_cancelar)
                    .addComponent(jb_actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_salir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_guardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_nuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_nuevo)
                .addGap(40, 40, 40)
                .addComponent(jb_borrar)
                .addGap(28, 28, 28)
                .addComponent(jb_modificar)
                .addGap(33, 33, 33)
                .addComponent(jb_salir)
                .addGap(34, 34, 34)
                .addComponent(jb_actualizar)
                .addGap(33, 33, 33)
                .addComponent(jb_guardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jb_cancelar)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        jb_primer_registro.setBackground(new java.awt.Color(0, 102, 255));
        jb_primer_registro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_primer_registro.setForeground(new java.awt.Color(255, 255, 255));
        jb_primer_registro.setText("|<");
        jb_primer_registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_primer_registroMouseClicked(evt);
            }
        });
        jb_primer_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_primer_registroActionPerformed(evt);
            }
        });

        jb_registro_anterior.setBackground(new java.awt.Color(0, 102, 255));
        jb_registro_anterior.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_registro_anterior.setForeground(new java.awt.Color(255, 255, 255));
        jb_registro_anterior.setText("<<");
        jb_registro_anterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_registro_anteriorMouseClicked(evt);
            }
        });

        jb_siguiente_registro.setBackground(new java.awt.Color(0, 102, 255));
        jb_siguiente_registro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_siguiente_registro.setForeground(new java.awt.Color(255, 255, 255));
        jb_siguiente_registro.setText(">>");
        jb_siguiente_registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_siguiente_registroMouseClicked(evt);
            }
        });
        jb_siguiente_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_siguiente_registroActionPerformed(evt);
            }
        });

        jb_ultimo_registro.setBackground(new java.awt.Color(0, 102, 255));
        jb_ultimo_registro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_ultimo_registro.setForeground(new java.awt.Color(255, 255, 255));
        jb_ultimo_registro.setText(">|");
        jb_ultimo_registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ultimo_registroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_primer_registro)
                .addGap(81, 81, 81)
                .addComponent(jb_registro_anterior)
                .addGap(96, 96, 96)
                .addComponent(jb_siguiente_registro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jb_ultimo_registro)
                .addGap(49, 49, 49))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_primer_registro)
                    .addComponent(jb_registro_anterior)
                    .addComponent(jb_siguiente_registro)
                    .addComponent(jb_ultimo_registro))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_marcaActionPerformed

    private void jb_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_guardarActionPerformed

    private void jb_primer_registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_primer_registroMouseClicked
        moverPrimerRegistro();// TODO add your handling code here:
    }//GEN-LAST:event_jb_primer_registroMouseClicked

    private void jb_registro_anteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_registro_anteriorMouseClicked
        moverRegistroAnterior();// TODO add your handling code here:
    }//GEN-LAST:event_jb_registro_anteriorMouseClicked

    private void jb_siguiente_registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_siguiente_registroMouseClicked
        moverRegistroSiguiente();// TODO add your handling code here:
    }//GEN-LAST:event_jb_siguiente_registroMouseClicked

    private void jb_ultimo_registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ultimo_registroMouseClicked
        moverUltimoRegistro();// TODO add your handling code here:
    }//GEN-LAST:event_jb_ultimo_registroMouseClicked

    private void jb_primer_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_primer_registroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_primer_registroActionPerformed

    private void jb_siguiente_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_siguiente_registroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_siguiente_registroActionPerformed

    private void jb_nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_nuevoMouseClicked
        jtf_codigo.setText("");
        jtf_codigo.setEditable(true);
        jtf_modelo.setText("");
        jtf_modelo.setEditable(true);
        jtf_marca.setText("");
        jtf_marca.setEditable(true);
        jtf_precio_compra.setText("");
        jtf_precio_compra.setEditable(true);
        jtf_precio_venta.setText("");
        jtf_precio_venta.setEditable(true);
        jtf_cantidad_productos.setText("");
        jtf_cantidad_productos.setEditable(true);
        jtf_talla.setText("");
        jtf_talla.setEditable(true);
        jtf_color.setText("");
        jtf_color.setEditable(true);
        jtf_fecha.setVisible(false);
        jl_fecha.setVisible(false);
        jb_nuevo.setVisible(false);
        jb_borrar.setVisible(false);
        jb_modificar.setVisible(false);
        jb_guardar.setEnabled(true);
        jb_cancelar.setEnabled(true);
        jb_primer_registro.setEnabled(false);
        jb_siguiente_registro.setEnabled(false);
        jb_registro_anterior.setEnabled(false);
        jb_ultimo_registro.setEnabled(false);
        jb_guardar.setVisible(true);
        jb_cancelar.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_nuevoMouseClicked

    private void jb_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_salirMouseClicked
        JFMenu_principal jf_menu_principal=new JFMenu_principal();
        jf_menu_principal.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jb_salirMouseClicked

    private void jb_actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_actualizarMouseClicked
        try {
            String codigo = this.jtf_codigo.getText();
            String modelo = this.jtf_modelo.getText();
            String marca = this.jtf_marca.getText();
            String precio_compra = this.jtf_precio_compra.getText();
            String precio_venta = this.jtf_precio_venta.getText();
            String cantidad_productos = this.jtf_cantidad_productos.getText();
            String talla = this.jtf_talla.getText();
            String color = this.jtf_color.getText();
            
            
            String sql = ("update prod_existencia set modelo='" +modelo+ "', marca='" +marca+ "', precio_de_compra='" +precio_compra+ "', precio_de_venta='" +precio_venta+ "', cantidad_prod='" +cantidad_productos+ "', talla='" +talla+ "', color='" +color+ "' where codigo='" +codigo+ "';");
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Se a actualizado el producto");
            this.Conectar();
            this.moverUltimoRegistro();
            jb_nuevo.setVisible(true);
            jb_borrar.setVisible(true);
            jb_modificar.setVisible(true);
            jb_primer_registro.setEnabled(true);
            jb_siguiente_registro.setEnabled(true);
            jb_registro_anterior.setEnabled(true);
            jb_ultimo_registro.setEnabled(true);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "no se a actualizado"+ex.getMessage());
        }// TODO add your handling code here:
    }//GEN-LAST:event_jb_actualizarMouseClicked

    private void jb_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarMouseClicked
        try {
            String codigo=this.jtf_codigo.getText(); 
            String modelo=this.jtf_modelo.getText(); 
            String marca=this.jtf_marca.getText(); 
            String precio_c=this.jtf_precio_compra.getText(); 
            String precio_v=this.jtf_precio_venta.getText(); 
            String cantidad=this.jtf_cantidad_productos.getText(); 
            String talla=this.jtf_talla.getText(); 
            String color=this.jtf_color.getText(); 
            st.executeUpdate("insert into prod_existencia(codigo,modelo,marca,precio_de_compra,precio_de_venta,cantidad_prod,talla,color)"+" values ('"+codigo+"','"+modelo+"','"+marca+"',"+precio_c+","+precio_v+","+cantidad+",'"+talla+"','"+color+"');");
            st.executeUpdate("insert into detalle_productos(codigo,modelo,marca,precio_compra,precio_venta,cantidad_prod,talla,color)"+" values ('"+codigo+"','"+modelo+"','"+marca+"',"+precio_c+","+precio_v+","+cantidad+",'"+talla+"','"+color+"');");
            
            jtf_codigo.setText("");
            jtf_codigo.setEditable(true);
            jtf_modelo.setText("");
            jtf_modelo.setEditable(true);
            jtf_marca.setText("");
            jtf_marca.setEditable(true);
            jtf_precio_compra.setText("");
            jtf_precio_compra.setEditable(true);
            jtf_precio_venta.setText("");
            jtf_precio_venta.setEditable(true);
            jtf_cantidad_productos.setText("");
            jtf_cantidad_productos.setEditable(true);
            jtf_talla.setText("");
            jtf_talla.setEditable(true);
            jtf_color.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(JFAaltas.class.getName()).log(Level.SEVERE, null, ex);
        }
            JOptionPane.showMessageDialog(null,"Se a guardado el producto");// TODO add your handling code here:
    }//GEN-LAST:event_jb_guardarMouseClicked

    private void jb_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_cancelarMouseClicked
        jb_nuevo.setEnabled(true);
        jb_borrar.setEnabled(true);
        jb_modificar.setEnabled(true);
        jb_guardar.setEnabled(true);
        jb_cancelar.setEnabled(true);
        jb_primer_registro.setEnabled(true);
        jb_siguiente_registro.setEnabled(true);
        jb_registro_anterior.setEnabled(true);
        jb_ultimo_registro.setEnabled(true);
        jb_guardar.setVisible(false);
        jb_actualizar.setVisible(false);
        jb_cancelar.setVisible(false);
        jb_nuevo.setVisible(true);
        jb_borrar.setVisible(true);
        jb_modificar.setVisible(true);
        Conectar();
        llenarDatos();
        deshabilitarEdicion();// TODO add your handling code here:
    }//GEN-LAST:event_jb_cancelarMouseClicked

    private void jb_borrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_borrarMouseClicked
        String codigo=jtf_codigo.getText();
        try{ 
           st.executeUpdate("delete from prod_existencia where codigo='"+codigo+"';");
           JOptionPane.showMessageDialog(null,"Se borro el producto");
           Conectar();

       } catch(SQLException err){ 
            JOptionPane.showMessageDialog(null,"Error "+err.getMessage()); 
        }// TODO add your handling code here:
    }//GEN-LAST:event_jb_borrarMouseClicked

    private void jb_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modificarMouseClicked
        habilitarEdicion();
        jb_nuevo.setVisible(false);
        jb_borrar.setVisible(false);
        jb_modificar.setVisible(false);
        jb_guardar.setEnabled(false);
        jb_actualizar.setVisible(true);
        jb_cancelar.setVisible(true);
        jb_primer_registro.setEnabled(false);
        jb_siguiente_registro.setEnabled(false);
        jb_registro_anterior.setEnabled(false);
        jb_ultimo_registro.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_jb_modificarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFAaltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFAaltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFAaltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFAaltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFAaltas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jb_actualizar;
    private javax.swing.JButton jb_borrar;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JButton jb_modificar;
    private javax.swing.JButton jb_nuevo;
    private javax.swing.JButton jb_primer_registro;
    private javax.swing.JButton jb_registro_anterior;
    private javax.swing.JButton jb_salir;
    private javax.swing.JButton jb_siguiente_registro;
    private javax.swing.JButton jb_ultimo_registro;
    private javax.swing.JLabel jl_cantidad_productos;
    private javax.swing.JLabel jl_codigo;
    private javax.swing.JLabel jl_color;
    private javax.swing.JLabel jl_fecha;
    private javax.swing.JLabel jl_marca;
    private javax.swing.JLabel jl_modelo;
    private javax.swing.JLabel jl_precio_compra;
    private javax.swing.JLabel jl_precio_venta;
    private javax.swing.JLabel jl_talla;
    private javax.swing.JTextField jtf_cantidad_productos;
    private javax.swing.JTextField jtf_codigo;
    private javax.swing.JTextField jtf_color;
    private javax.swing.JTextField jtf_fecha;
    private javax.swing.JTextField jtf_marca;
    private javax.swing.JTextField jtf_modelo;
    private javax.swing.JTextField jtf_precio_compra;
    private javax.swing.JTextField jtf_precio_venta;
    private javax.swing.JTextField jtf_talla;
    // End of variables declaration//GEN-END:variables
}
