package formulario;

import com.mysql.jdbc.PreparedStatement;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Felix
 */
public class JFProveedores extends javax.swing.JFrame {

    private Connection conexion;
    private Statement st;
    private ResultSet rs;

    public void Conectar() {
        try {
            conexion = DriverManager.getConnection("jdbc:mysql://localhost:3307/proyecto", "root", "");
            st = conexion.createStatement();
            rs = st.executeQuery("Select * from proveedores");

            rs.next();
            
            this.jtf_id.setText(rs.getString("id"));
            this.jtf_rfc.setText(rs.getString("rfc"));
            this.jtf_calle.setText(rs.getString("calle"));
            this.jtf_numero.setText(rs.getString("numero"));
            this.jtf_colonia.setText(rs.getString("colonia"));
            this.jtf_ciudad.setText(rs.getString("ciudad"));
            this.jtf_telefono.setText(rs.getString("telefono"));
            this.jtf_nombres.setText(rs.getString("nombres"));
            this.jtf_apellido_p.setText(rs.getString("ap_p"));
            this.jtf_apellido_m.setText(rs.getString("ap_m"));
            jb_guardar.setVisible(false);
            jb_actualizar.setVisible(false);
            jb_cancelar.setVisible(false);
            jtf_id.setVisible(false);
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error" + err.getMessage());
        }
    }

    /**
     * Creates new form proveedores
     */
    public JFProveedores() {
        initComponents();
        this.Conectar();
    }

    public void moverPrimerRegistro() {
        try {
            rs.first();
            llenarDatos();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error 001" + ex.getMessage());
        }
    }

    public void moverRegistroSiguiente() {
        try {
            if (!rs.isLast()) {
                rs.next();
                llenarDatos();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error 001" + ex.getMessage());
        }
    }

    public void moverRegistroAnterior() {
        try {
            if (!rs.isFirst()) {
                rs.previous();
                llenarDatos();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error 001" + ex.getMessage());
        }
    }

    public void moverUltimoRegistro() {
        try {
            rs.last();
            llenarDatos();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error 001" + ex.getMessage());
        }
    }

    public void llenarDatos() {
        try {
            this.jtf_id.setText(rs.getString("id"));
            this.jtf_rfc.setText(rs.getString("rfc"));
            this.jtf_calle.setText(rs.getString("calle"));
            this.jtf_numero.setText(rs.getString("numero"));
            this.jtf_colonia.setText(rs.getString("colonia"));
            this.jtf_ciudad.setText(rs.getString("ciudad"));
            this.jtf_telefono.setText(rs.getString("telefono"));
            this.jtf_nombres.setText(rs.getString("nombres"));
            this.jtf_apellido_p.setText(rs.getString("ap_p"));
            this.jtf_apellido_m.setText(rs.getString("ap_m"));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error 002" + ex.getMessage());
        }
    }

    public void deshabilitarEdicion() {
        jtf_rfc.setEditable(false);
        jtf_calle.setEditable(false);
        jtf_numero.setEditable(false);
        jtf_colonia.setEditable(false);
        jtf_ciudad.setEditable(false);
        jtf_telefono.setEditable(false);
        jtf_nombres.setEditable(false);
        jtf_apellido_p.setEditable(false);
        jtf_apellido_m.setEditable(false);
    }

    public void habilitarEdicion() {
        jtf_rfc.setEditable(false);
        jtf_rfc.setEditable(true);
        jtf_calle.setEditable(true);
        jtf_numero.setEditable(true);
        jtf_colonia.setEditable(true);
        jtf_ciudad.setEditable(true);
        jtf_telefono.setEditable(true);
        jtf_nombres.setEditable(true);
        jtf_apellido_p.setEditable(true);
        jtf_apellido_m.setEditable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jl_rfc = new javax.swing.JLabel();
        jl_calle = new javax.swing.JLabel();
        jl_numero = new javax.swing.JLabel();
        jl_colonia = new javax.swing.JLabel();
        jl_ciudad = new javax.swing.JLabel();
        jl_telefono = new javax.swing.JLabel();
        jl_nombres = new javax.swing.JLabel();
        jl_apellido_p = new javax.swing.JLabel();
        jl_apellido_m = new javax.swing.JLabel();
        jtf_rfc = new javax.swing.JTextField();
        jtf_calle = new javax.swing.JTextField();
        jtf_numero = new javax.swing.JTextField();
        jtf_colonia = new javax.swing.JTextField();
        jtf_ciudad = new javax.swing.JTextField();
        jtf_telefono = new javax.swing.JTextField();
        jtf_nombres = new javax.swing.JTextField();
        jtf_apellido_p = new javax.swing.JTextField();
        jtf_apellido_m = new javax.swing.JTextField();
        jtf_id = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jb_nuevo = new javax.swing.JButton();
        jb_borrar = new javax.swing.JButton();
        jb_modificar = new javax.swing.JButton();
        jb_guardar = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();
        jb_actualizar = new javax.swing.JButton();
        jb_salir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jb_primer_registro = new javax.swing.JButton();
        jb_registro_anterior = new javax.swing.JButton();
        jb_siguiente_registro = new javax.swing.JButton();
        jb_ultimo_registro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/Resize Image_1533787075919.jpg"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(0, 0, 153));
        jLabel1.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PROVEEDORES");
        jLabel1.setFocusTraversalPolicyProvider(true);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jl_rfc.setBackground(new java.awt.Color(153, 204, 255));
        jl_rfc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_rfc.setText("RFC");
        jl_rfc.setOpaque(true);

        jl_calle.setBackground(new java.awt.Color(153, 204, 255));
        jl_calle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_calle.setText("Calle");
        jl_calle.setOpaque(true);

        jl_numero.setBackground(new java.awt.Color(153, 204, 255));
        jl_numero.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_numero.setText("Numero");
        jl_numero.setOpaque(true);

        jl_colonia.setBackground(new java.awt.Color(153, 204, 255));
        jl_colonia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_colonia.setText("Colonia");
        jl_colonia.setOpaque(true);

        jl_ciudad.setBackground(new java.awt.Color(153, 204, 255));
        jl_ciudad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_ciudad.setText("Ciudad");
        jl_ciudad.setOpaque(true);

        jl_telefono.setBackground(new java.awt.Color(153, 204, 255));
        jl_telefono.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_telefono.setText("Telefono");
        jl_telefono.setOpaque(true);

        jl_nombres.setBackground(new java.awt.Color(153, 204, 255));
        jl_nombres.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_nombres.setText("Nombre(s)");
        jl_nombres.setOpaque(true);

        jl_apellido_p.setBackground(new java.awt.Color(153, 204, 255));
        jl_apellido_p.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_apellido_p.setText("Apellido paterno");
        jl_apellido_p.setOpaque(true);

        jl_apellido_m.setBackground(new java.awt.Color(153, 204, 255));
        jl_apellido_m.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_apellido_m.setText("Apellido materno");
        jl_apellido_m.setOpaque(true);

        jtf_rfc.setEditable(false);
        jtf_rfc.setBackground(new java.awt.Color(153, 255, 255));
        jtf_rfc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jtf_calle.setEditable(false);
        jtf_calle.setBackground(new java.awt.Color(153, 255, 255));
        jtf_calle.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jtf_numero.setEditable(false);
        jtf_numero.setBackground(new java.awt.Color(153, 255, 255));
        jtf_numero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jtf_colonia.setEditable(false);
        jtf_colonia.setBackground(new java.awt.Color(153, 255, 255));
        jtf_colonia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtf_colonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_coloniaActionPerformed(evt);
            }
        });

        jtf_ciudad.setEditable(false);
        jtf_ciudad.setBackground(new java.awt.Color(153, 255, 255));
        jtf_ciudad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jtf_telefono.setEditable(false);
        jtf_telefono.setBackground(new java.awt.Color(153, 255, 255));
        jtf_telefono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jtf_nombres.setEditable(false);
        jtf_nombres.setBackground(new java.awt.Color(153, 255, 255));
        jtf_nombres.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jtf_apellido_p.setEditable(false);
        jtf_apellido_p.setBackground(new java.awt.Color(153, 255, 255));
        jtf_apellido_p.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jtf_apellido_m.setEditable(false);
        jtf_apellido_m.setBackground(new java.awt.Color(153, 255, 255));
        jtf_apellido_m.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jtf_id.setEditable(false);
        jtf_id.setBackground(new java.awt.Color(153, 255, 255));
        jtf_id.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_rfc)
                    .addComponent(jl_calle)
                    .addComponent(jl_numero)
                    .addComponent(jl_colonia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtf_colonia, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(jtf_calle, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_rfc, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_numero)
                    .addComponent(jtf_id, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_ciudad)
                    .addComponent(jl_telefono)
                    .addComponent(jl_nombres)
                    .addComponent(jl_apellido_p)
                    .addComponent(jl_apellido_m))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_apellido_p, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(jtf_nombres, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtf_telefono)
                    .addComponent(jtf_ciudad)
                    .addComponent(jtf_apellido_m))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_rfc)
                    .addComponent(jtf_rfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_calle)
                    .addComponent(jtf_calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_numero)
                    .addComponent(jtf_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_colonia)
                    .addComponent(jtf_colonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_ciudad)
                    .addComponent(jtf_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_telefono)
                    .addComponent(jtf_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nombres)
                    .addComponent(jtf_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_apellido_p)
                    .addComponent(jtf_apellido_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_apellido_m)
                    .addComponent(jtf_apellido_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jb_nuevo.setBackground(new java.awt.Color(51, 0, 255));
        jb_nuevo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        jb_nuevo.setText("Nuevo");
        jb_nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_nuevoMouseClicked(evt);
            }
        });

        jb_borrar.setBackground(new java.awt.Color(51, 51, 255));
        jb_borrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_borrar.setForeground(new java.awt.Color(255, 255, 255));
        jb_borrar.setText("Borrar");
        jb_borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_borrarMouseClicked(evt);
            }
        });

        jb_modificar.setBackground(new java.awt.Color(51, 0, 255));
        jb_modificar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_modificar.setForeground(new java.awt.Color(255, 255, 255));
        jb_modificar.setText("Modificar");
        jb_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modificarMouseClicked(evt);
            }
        });

        jb_guardar.setBackground(new java.awt.Color(51, 0, 255));
        jb_guardar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_guardar.setForeground(new java.awt.Color(255, 255, 255));
        jb_guardar.setText("Guardar");
        jb_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarMouseClicked(evt);
            }
        });
        jb_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_guardarActionPerformed(evt);
            }
        });

        jb_cancelar.setBackground(new java.awt.Color(51, 0, 204));
        jb_cancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        jb_cancelar.setText("Cancelar");
        jb_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_cancelarMouseClicked(evt);
            }
        });

        jb_actualizar.setBackground(new java.awt.Color(51, 0, 255));
        jb_actualizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_actualizar.setForeground(new java.awt.Color(255, 255, 255));
        jb_actualizar.setText("Actualizar");
        jb_actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_actualizarMouseClicked(evt);
            }
        });

        jb_salir.setBackground(new java.awt.Color(51, 0, 255));
        jb_salir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_salir.setForeground(new java.awt.Color(255, 255, 255));
        jb_salir.setText("Salir");
        jb_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_salirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_nuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_nuevo)
                .addGap(37, 37, 37)
                .addComponent(jb_borrar)
                .addGap(41, 41, 41)
                .addComponent(jb_modificar)
                .addGap(27, 27, 27)
                .addComponent(jb_salir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jb_actualizar)
                .addGap(30, 30, 30)
                .addComponent(jb_guardar)
                .addGap(30, 30, 30)
                .addComponent(jb_cancelar)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        jb_primer_registro.setBackground(new java.awt.Color(0, 102, 255));
        jb_primer_registro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_primer_registro.setForeground(new java.awt.Color(255, 255, 255));
        jb_primer_registro.setText("|<");
        jb_primer_registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_primer_registroMouseClicked(evt);
            }
        });
        jb_primer_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_primer_registroActionPerformed(evt);
            }
        });

        jb_registro_anterior.setBackground(new java.awt.Color(0, 102, 255));
        jb_registro_anterior.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_registro_anterior.setForeground(new java.awt.Color(255, 255, 255));
        jb_registro_anterior.setText("<<");
        jb_registro_anterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_registro_anteriorMouseClicked(evt);
            }
        });

        jb_siguiente_registro.setBackground(new java.awt.Color(0, 102, 255));
        jb_siguiente_registro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_siguiente_registro.setForeground(new java.awt.Color(255, 255, 255));
        jb_siguiente_registro.setText(">>");
        jb_siguiente_registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_siguiente_registroMouseClicked(evt);
            }
        });
        jb_siguiente_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_siguiente_registroActionPerformed(evt);
            }
        });

        jb_ultimo_registro.setBackground(new java.awt.Color(0, 102, 255));
        jb_ultimo_registro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_ultimo_registro.setForeground(new java.awt.Color(255, 255, 255));
        jb_ultimo_registro.setText(">|");
        jb_ultimo_registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ultimo_registroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_primer_registro)
                .addGap(81, 81, 81)
                .addComponent(jb_registro_anterior)
                .addGap(96, 96, 96)
                .addComponent(jb_siguiente_registro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jb_ultimo_registro)
                .addGap(49, 49, 49))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_primer_registro)
                    .addComponent(jb_registro_anterior)
                    .addComponent(jb_siguiente_registro)
                    .addComponent(jb_ultimo_registro))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_coloniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_coloniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_coloniaActionPerformed

    private void jb_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_guardarActionPerformed

    private void jb_primer_registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_primer_registroMouseClicked
        moverPrimerRegistro();// TODO add your handling code here:
    }//GEN-LAST:event_jb_primer_registroMouseClicked

    private void jb_primer_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_primer_registroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_primer_registroActionPerformed

    private void jb_registro_anteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_registro_anteriorMouseClicked
        moverRegistroAnterior();// TODO add your handling code here:
    }//GEN-LAST:event_jb_registro_anteriorMouseClicked

    private void jb_siguiente_registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_siguiente_registroMouseClicked
        moverRegistroSiguiente();// TODO add your handling code here:
    }//GEN-LAST:event_jb_siguiente_registroMouseClicked

    private void jb_siguiente_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_siguiente_registroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_siguiente_registroActionPerformed

    private void jb_ultimo_registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ultimo_registroMouseClicked
        moverUltimoRegistro();// TODO add your handling code here:
    }//GEN-LAST:event_jb_ultimo_registroMouseClicked

    private void jb_nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_nuevoMouseClicked
        jtf_rfc.setText("");
        jtf_rfc.setEditable(true);
        jtf_calle.setText("");
        jtf_calle.setEditable(true);
        jtf_numero.setText("");
        jtf_numero.setEditable(true);
        jtf_colonia.setText("");
        jtf_colonia.setEditable(true);
        jtf_ciudad.setText("");
        jtf_ciudad.setEditable(true);
        jtf_telefono.setText("");
        jtf_telefono.setEditable(true);
        jtf_nombres.setText("");
        jtf_nombres.setEditable(true);
        jtf_apellido_p.setText("");
        jtf_apellido_p.setEditable(true);
        jtf_apellido_m.setText("");
        jtf_apellido_m.setEditable(true);
        jb_nuevo.setVisible(false);
        jb_borrar.setVisible(false);
        jb_modificar.setVisible(false);
        jb_guardar.setEnabled(true);
        jb_cancelar.setEnabled(true);
        jb_primer_registro.setEnabled(false);
        jb_siguiente_registro.setEnabled(false);
        jb_registro_anterior.setEnabled(false);
        jb_ultimo_registro.setEnabled(false);
        jb_guardar.setVisible(true);
        jb_cancelar.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jb_nuevoMouseClicked

    private void jb_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarMouseClicked
        try {
            String rfc = this.jtf_rfc.getText();
            String calle = this.jtf_calle.getText();
            String numero = this.jtf_numero.getText();
            String colonia = this.jtf_colonia.getText();
            String ciudad = this.jtf_ciudad.getText();
            String telefono = this.jtf_telefono.getText();
            String nombres = this.jtf_nombres.getText();
            String apellido_p = this.jtf_apellido_p.getText();
            String apellido_m = this.jtf_apellido_m.getText();

            st.executeUpdate("Insert into proveedores (rfc,calle,numero,colonia,ciudad,telefono,nombres,ap_p,ap_m)" + " values ('" + rfc + "','" + calle + "','" + numero + "','" + colonia + "','" + ciudad + "','" + telefono + "','" + nombres + "','" + apellido_p + "','" + apellido_m + "');");
            JOptionPane.showMessageDialog(null, "Se a guardado el proveedor");
            jtf_rfc.setText("");
            jtf_rfc.setEditable(true);
            jtf_calle.setText("");
            jtf_calle.setEditable(true);
            jtf_numero.setText("");
            jtf_numero.setEditable(true);
            jtf_colonia.setText("");
            jtf_colonia.setEditable(true);
            jtf_ciudad.setText("");
            jtf_ciudad.setEditable(true);
            jtf_telefono.setText("");
            jtf_telefono.setEditable(true);
            jtf_nombres.setText("");
            jtf_nombres.setEditable(true);
            jtf_apellido_p.setText("");
            jtf_apellido_p.setEditable(true);
            jtf_apellido_m.setText("");

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        } // TODO add your handling code here:
    }//GEN-LAST:event_jb_guardarMouseClicked

    private void jb_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_cancelarMouseClicked
        jb_nuevo.setEnabled(true);
        jb_borrar.setEnabled(true);
        jb_modificar.setEnabled(true);
        jb_guardar.setEnabled(true);
        jb_cancelar.setEnabled(true);
        jb_primer_registro.setEnabled(true);
        jb_siguiente_registro.setEnabled(true);
        jb_registro_anterior.setEnabled(true);
        jb_ultimo_registro.setEnabled(true);
        jb_guardar.setVisible(false);
        jb_actualizar.setVisible(false);
        jb_cancelar.setVisible(false);
        jb_nuevo.setVisible(true);
        jb_borrar.setVisible(true);
        jb_modificar.setVisible(true);
        Conectar();
        llenarDatos();
        deshabilitarEdicion();

        // TODO add your handling code here:
    }//GEN-LAST:event_jb_cancelarMouseClicked

    private void jb_borrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_borrarMouseClicked
        String rfc = jtf_rfc.getText();
        try {
            st.executeUpdate("delete from proveedores where rfc='" + rfc + "';");
            JOptionPane.showMessageDialog(null, "Se borro el proveedor");
            Conectar();
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_borrarMouseClicked

    private void jb_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modificarMouseClicked
        habilitarEdicion();
        jb_nuevo.setVisible(false);
        jb_borrar.setVisible(false);
        jb_modificar.setVisible(false);
        jb_guardar.setEnabled(false);
        jb_actualizar.setVisible(true);
        jb_cancelar.setVisible(true);
        jb_primer_registro.setEnabled(false);
        jb_siguiente_registro.setEnabled(false);
        jb_registro_anterior.setEnabled(false);
        jb_ultimo_registro.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_modificarMouseClicked

    private void jb_actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_actualizarMouseClicked

        try {
            String id = this.jtf_id.getText();
            String rfc = this.jtf_rfc.getText();
            String calle = this.jtf_calle.getText();
            String numero = this.jtf_numero.getText();
            String colonia = this.jtf_colonia.getText();
            String ciudad = this.jtf_ciudad.getText();
            String telefono = this.jtf_telefono.getText();
            String nombres = this.jtf_nombres.getText();
            String apellido_p = this.jtf_apellido_p.getText();
            String apellido_m = this.jtf_apellido_m.getText();

            String sql = ("update proveedores set rfc='" + rfc+ "', calle='" + calle + "', numero='" + numero + "', colonia='" + colonia + "', ciudad='" + ciudad + "', telefono='" + telefono + "', nombres='" + nombres + "', ap_p='" + apellido_p + "', ap_m='" + apellido_m + "' where id='" + id + "';");
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Se a actualizado el proveedor");
            this.Conectar();
            this.moverUltimoRegistro();
            jb_nuevo.setVisible(true);
            jb_borrar.setVisible(true);
            jb_modificar.setVisible(true);
            jb_primer_registro.setEnabled(true);
            jb_siguiente_registro.setEnabled(true);
            jb_registro_anterior.setEnabled(true);
            jb_ultimo_registro.setEnabled(true);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "no se a actualizado"+ex.getMessage());
        }


    }//GEN-LAST:event_jb_actualizarMouseClicked

    private void jb_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_salirMouseClicked
        JFMenu_principal jf_menu_principal = new JFMenu_principal();
        jf_menu_principal.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jb_salirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFProveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jb_actualizar;
    private javax.swing.JButton jb_borrar;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JButton jb_modificar;
    private javax.swing.JButton jb_nuevo;
    private javax.swing.JButton jb_primer_registro;
    private javax.swing.JButton jb_registro_anterior;
    private javax.swing.JButton jb_salir;
    private javax.swing.JButton jb_siguiente_registro;
    private javax.swing.JButton jb_ultimo_registro;
    private javax.swing.JLabel jl_apellido_m;
    private javax.swing.JLabel jl_apellido_p;
    private javax.swing.JLabel jl_calle;
    private javax.swing.JLabel jl_ciudad;
    private javax.swing.JLabel jl_colonia;
    private javax.swing.JLabel jl_nombres;
    private javax.swing.JLabel jl_numero;
    private javax.swing.JLabel jl_rfc;
    private javax.swing.JLabel jl_telefono;
    private javax.swing.JTextField jtf_apellido_m;
    private javax.swing.JTextField jtf_apellido_p;
    private javax.swing.JTextField jtf_calle;
    private javax.swing.JTextField jtf_ciudad;
    private javax.swing.JTextField jtf_colonia;
    private javax.swing.JTextField jtf_id;
    private javax.swing.JTextField jtf_nombres;
    private javax.swing.JTextField jtf_numero;
    private javax.swing.JTextField jtf_rfc;
    private javax.swing.JTextField jtf_telefono;
    // End of variables declaration//GEN-END:variables
}
